-- MySQL Script generated by MySQL Workbench
-- 02/02/16 15:41:27
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema systemdesigner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema systemdesigner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `systemdesigner` DEFAULT CHARACTER SET utf8 ;
USE `systemdesigner` ;

-- -----------------------------------------------------
-- Table `systemdesigner`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`role` (
  `role_id` CHAR(10) NOT NULL,
  `role_name` VARCHAR(45) NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`person` (
  `person_id` CHAR(10) NOT NULL,
  `person_name` VARCHAR(45) NOT NULL,
  `telephone` CHAR(15) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`person_id`),
  INDEX `fk_person_role_idx` (`role_id` ASC),
  CONSTRAINT `fk_person_role`
    FOREIGN KEY (`role_id`)
    REFERENCES `systemdesigner`.`role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`medicine_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`medicine_type` (
  `medicine_type_id` CHAR(10) NOT NULL,
  `medicine_type_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`medicine_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`finance_report`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`finance_report` (
  `finance_report_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`finance_report_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`medicine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`medicine` (
  `medicine_id` CHAR(10) NOT NULL,
  `medicine_name` VARCHAR(50) NOT NULL,
  `medicine_sale_price` DOUBLE NOT NULL,
  `store` INT NOT NULL,
  `medicine_type_id` CHAR(10) NOT NULL,
  `finance_report_finance_report_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`medicine_id`),
  INDEX `fk_medicine_medicinetype1_idx` (`medicine_type_id` ASC),
  INDEX `fk_medicine_finance_report1_idx` (`finance_report_finance_report_id` ASC),
  CONSTRAINT `fk_medicine_medicinetype1`
    FOREIGN KEY (`medicine_type_id`)
    REFERENCES `systemdesigner`.`medicine_type` (`medicine_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medicine_finance_report1`
    FOREIGN KEY (`finance_report_finance_report_id`)
    REFERENCES `systemdesigner`.`finance_report` (`finance_report_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`order` (
  `order_id` CHAR(10) NOT NULL,
  `order_date` DATETIME(6) NOT NULL,
  `order_price` DOUBLE NOT NULL,
  `person_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_order_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_order_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `systemdesigner`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`order_item` (
  `order_item_id` CHAR(10) NOT NULL,
  `number` INT NOT NULL,
  `order_item_price` DOUBLE NOT NULL,
  `order_id` CHAR(10) NOT NULL,
  `medicine_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_order_item_order1_idx` (`order_id` ASC),
  INDEX `fk_order_item_medicine1_idx` (`medicine_id` ASC),
  CONSTRAINT `fk_order_item_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `systemdesigner`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_medicine1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `systemdesigner`.`medicine` (`medicine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`sale_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`sale_record` (
  `sale_record_id` CHAR(10) NOT NULL,
  `sale_record_price` VARCHAR(45) NOT NULL,
  `sale_record_date` DATETIME(6) NOT NULL,
  `person_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`sale_record_id`),
  INDEX `fk_sale_record_person1_idx` (`person_id` ASC),
  CONSTRAINT `fk_sale_record_person1`
    FOREIGN KEY (`person_id`)
    REFERENCES `systemdesigner`.`person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `systemdesigner`.`sale_record_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `systemdesigner`.`sale_record_item` (
  `sale_record_item_id` CHAR(10) NOT NULL,
  `sale_record_number` INT NULL,
  `sale_record_id` CHAR(10) NOT NULL,
  `medicine_id` CHAR(10) NOT NULL,
  PRIMARY KEY (`sale_record_item_id`),
  INDEX `fk_sale_record_item_sale_record1_idx` (`sale_record_id` ASC),
  INDEX `fk_sale_record_item_medicine1_idx` (`medicine_id` ASC),
  CONSTRAINT `fk_sale_record_item_sale_record1`
    FOREIGN KEY (`sale_record_id`)
    REFERENCES `systemdesigner`.`sale_record` (`sale_record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_record_item_medicine1`
    FOREIGN KEY (`medicine_id`)
    REFERENCES `systemdesigner`.`medicine` (`medicine_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
