/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '16-11-21 下午2:53' with Gradle 2.11
 *
 * @author Administrator, @date 16-11-21 下午2:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
